markdown: kramdown
multiply: 2.5
session: 2016-2017
exam: Inhouse Exams , June 2016
semester: Part I  , Semester I
class: M.Sc. Mathematics
subject: Field Theory (Math14-101)
include: [_redirects]
tablecolor: warning
alertcolor: danger
buttoncolor: info